services:
  bitwarden-mxroute-server:
    container_name: bitwarden-mxroute-server
    image: ghcr.io/bfpimentel/bitwarden-mxroute-server:latest
    ports:
      - "6123:6123"
    env_file: .env.prod
  bitwarden-mxroute-web:
    container_name: bitwarden-mxroute-web
    image: ghcr.io/bfpimentel/bitwarden-mxroute-web:latest
    ports:
      - "6124:6124"
    env_file: .env.prod
    depends_on:
      - bitwarden-mxroute-server
