services:
  mxroute-bitwarden-server:
    container_name: mxroute-bitwarden-server
    build:
      context: .
      dockerfile: server/Dockerfile.dev
    ports:
      - "6123:6123"
    env_file: .env.dev
