services:
  mxroute-bitwarden-server:
    container_name: mxroute-bitwarden-server
    image: ghcr.io/bfpimentel/mxroute-bitwarden-server:latest
    ports:
      - "6123:6123"
    env_file: .env.example
  mxroute-bitwarden-web:
    container_name: mxroute-bitwarden-web
    image: ghcr.io/bfpimentel/mxroute-bitwarden-web:latest
    ports:
      - "6124:6124"
    env_file: .env.example
    depends_on:
      - mxroute-bitwarden-server
