services:
  mxroute-bitwarden-server:
    container_name: mxroute-bitwarden-server
    image: ghcr.io/bfpimentel/mxroute-bitwarden-server:latest
    ports:
      - "6123:6123"
    env_file: .env.example
