services:
  mxroute-bitwarden-server:
    container_name: mxroute-bitwarden-server
    build:
      context: .
      dockerfile: server/Dockerfile.dev
    ports:
      - "6123:6123"
    env_file: .env.dev
  mxroute-bitwarden-web:
    container_name: mxroute-bitwarden-web
    build:
      context: .
      dockerfile: web/Dockerfile.dev
    ports:
      - "6124:6124"
    env_file: .env.dev
    depends_on:
      - mxroute-bitwarden-server
